name: deploy
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.go'
      - 'public/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o perfectworld ./cmd/server
      - name: Copy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "perfectworld,public/**"
          target: "/root/perfectworld"
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart perfectworld
            sudo systemctl status perfectworld --no-pager || true
